### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by invaderzim1234** [Aeywoo/WTDR#1]
[game] Trigger action 'Tarniyar.CP.WalkToDesert_MigrateIds' has action string 'Pathoschild.ContentPatcher_MigrateIds Items JsonAssets:objects:Eerie Seeds (O)Tarniyar.CP.WalkToDesert_Eerie_Plant_Seeds JsonAssets:objects:Ghost Berry (O)Tarniyar.CP.WalkToDesert_Ghost_Berry JsonAssets:objects:Ghostly Wine (O)Tarniyar.CP.WalkToDesert_Ghostly_Wine JsonAssets:objects:Giant Old Coin (O)Tarniyar.CP.WalkToDesert_Giant_Old_Coin JsonAssets:objects:Old Coin (O)Tarniyar.CP.WalkToDesert_Old_Coin' which couldn't be applied: the old item ID "JsonAssets:objects:Eerie Seeds" must be a qualified item ID (like (O)JsonAssets:objects:Eerie Seeds).

new game
four corners farm
7 cabins
separate money

year 1 completable
monsters spawn on farm

[SMAPI LOG.txt](https://github.com/Aeywoo/WTDR/files/14844098/SMAPI.LOG.txt)

**Comment by Aeywoo** [comment]
Hey thanks for the bug report, I've been experiencing this myself. The MigrateIds feature for JsonAssets items being converted to Content Patcher is still being worked on by Pathoschild and the feature I'm using for WTDR is only available if you use the Alpha Build of Content Patcher 2.10.0, so you can just ignore it as it doesn't affect the mods functions, but if you would like to try using this Alpha build of Content Patcher 2.10.0 you can get it from here: https://discord.com/channels/137344473976799233/156109690059751424/1223507940443557928

**Comment by invaderzim1234** [comment]
alpha build of content patcher installed, thanks for the link

 same world one in-game month and 9 days later.

[game] Location 'Custom_DTZ_ZuzuCityFreeway1' failed to load seasonal asset name 'SMAPI\tarniyar.cp.walktodesert\assets\maps\patches\summer_extra3.png' for tilesheet ID 'z_spring_extra3'.
SContentLoadException: Failed loading asset 'assets/maps/patches/summer_extra3.png' from SMAPI\tarniyar.cp.walktodesert: the specified path doesn't exist.
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.ThrowLoadError(IAssetName assetName, ContentLoadErrorType errorType, String reasonPhrase, Exception exception) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 319
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadExact[T](IAssetName assetName, Boolean useCache) in SMAPI\Framework\ContentManagers\ModContentManager.cs:line 114
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.LoadExact[T](IAssetName assetName, Boolean useCache)
   at StardewValley.LocalizedContentManager.Load[T](String assetName, LanguageCode language) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\LocalizedContentManager.cs:line 524
   at StardewModdingAPI.Framework.Rendering.SXnaDisplayDevice.LoadTileSheet(TileSheet tileSheet) in SMAPI\Framework\Rendering\SXnaDisplayDevice.cs:line 55
   at StardewValley.GameLocation.updateSeasonalTileSheets(Map map) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:line 17106

[SMAPI LOG.txt](https://github.com/Aeywoo/WTDR/files/14859036/SMAPI.LOG.txt)

not sure if this is another issue you are aware of. but it happens after loading into the game from a save in summer, when the game transitioned to summer this error hadn't appeared.

**Comment by invaderzim1234** [comment]
just installed the update, the two errors i was receiving before are now gone!!!!

**Comment by Aeywoo** [comment]
Yeah, seems Pathos fixed the issues now with MigrateIds, and I resolved the issue with the Downtown Zuzu patch by manually editing the tiles via content.json.
